// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPersonOn1Change();
void onPersonOn2Change();

bool person_on1;
bool person_on2;

void initProperties(){

  ArduinoCloud.addProperty(person_on1, READWRITE, ON_CHANGE, onPersonOn1Change);
  ArduinoCloud.addProperty(person_on2, READWRITE, ON_CHANGE, onPersonOn2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
